# Generated by Django 3.0.7 on 2020-07-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0002_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='genderhaha',
        ),
    ]
