# Generated by Django 3.0.7 on 2020-07-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0003_auto_20200701_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='name',
        ),
        migrations.AddField(
            model_name='gender',
            name='url',
            field=models.CharField(default='http://www.example.com', max_length=100, verbose_name='门户地址'),
        ),
    ]
