# Generated by Django 3.0.7 on 2020-07-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0004_auto_20200701_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
