# Generated by Django 3.0.7 on 2020-07-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0005_delete_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Resource',
        ),
    ]
