# Generated by Django 3.0.7 on 2020-07-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0006_auto_20200701_1707'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource',
            table='resource',
        ),
    ]
