# Generated by Django 3.0.7 on 2020-07-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0007_auto_20200701_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': (('can_visit_res', 'Can visit this host'),)},
        ),
    ]
