# Generated by Django 3.0.7 on 2020-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0008_auto_20200701_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='url',
            new_name='name',
        ),
        migrations.AddField(
            model_name='resource',
            name='codename',
            field=models.CharField(default='example', max_length=100, verbose_name='门户代码'),
        ),
    ]
